SUPABASE_URL = "https://mnqfojbkscjdjqzejjpe.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ucWZvamJrc2NqZGpxemVqanBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMDc0NTIsImV4cCI6MjA1OTc4MzQ1Mn0.n8Pi5OBferrerQ3CixtNGuMo2q53sCj_7N7B8HY83P8"
ADMIN_EMAIL = "patelajays@gmail.com"